import { MenuItem, ServiceItem } from './types';

export const NAV_LINKS = [
  { name: 'Cafe', href: '#menu' },
  { name: 'Pastries', href: '#menu' },
  { name: 'Food', href: '#menu' },
  { name: 'Reserve Table', href: '#reservation' },
];

export const SERVICES: ServiceItem[] = [
  {
    id: '1',
    title: 'Breakfast & Brunch',
    description: 'Start your day with Rwandan tea, fresh chapati, and tropical fruits from the local market.',
    image: 'https://picsum.photos/id/1060/400/500',
  },
  {
    id: '2',
    title: 'Traditional Lunch',
    description: 'Experience authentic flavors with our signature Agatogo and Isombe dishes.',
    image: 'https://picsum.photos/id/1080/400/500',
  },
  {
    id: '3',
    title: 'Evening Grills',
    description: 'Enjoy the finest goat brochettes and grilled tilapia under the Kigali stars.',
    image: 'https://picsum.photos/id/431/400/500',
  },
];

export const MENU_ITEMS: MenuItem[] = [
  // Hot Drinks
  { id: 'h1',  name: 'Espresso',             description: 'Rich single-origin Rwandan espresso shot.',            price: '3,500', category: 'hot-drinks',  image: 'https://picsum.photos/id/431/100/100' },
  { id: 'h2',  name: 'Espresso Macchiato',   description: 'Espresso topped with a dash of foamed milk.',          price: '4,000', category: 'hot-drinks',  image: 'https://picsum.photos/id/425/100/100' },
  { id: 'h3',  name: 'Americano',            description: 'Espresso diluted with hot water for a milder taste.',  price: '4,500', category: 'hot-drinks',  image: 'https://picsum.photos/id/1060/100/100' },
  { id: 'h4',  name: 'Pour Over (Chemex/V60)', description: 'Slow-brewed single origin pour over coffee.',        price: '5,000', category: 'hot-drinks',  image: 'https://picsum.photos/id/432/100/100' },
  { id: 'h5',  name: 'Aeropress',            description: 'Full-bodied coffee brewed with Aeropress method.',     price: '5,000', category: 'hot-drinks',  image: 'https://picsum.photos/id/61/100/100' },
  { id: 'h6',  name: 'French Press',         description: 'Classic immersion brew, bold and full-flavored.',      price: '5,000', category: 'hot-drinks',  image: 'https://picsum.photos/id/425/100/100' },
  { id: 'h7',  name: 'African Espresso',     description: 'Double espresso with African spice blend.',            price: '6,000', category: 'hot-drinks',  image: 'https://picsum.photos/id/431/100/100' },
  { id: 'h8',  name: 'Cortado',              description: 'Equal parts espresso and warm milk.',                  price: '4,500', category: 'hot-drinks',  image: 'https://picsum.photos/id/1060/100/100' },
  { id: 'h9',  name: 'Cappuccino',           description: 'Espresso with steamed milk and thick foam.',           price: '5,000', category: 'hot-drinks',  image: 'https://picsum.photos/id/432/100/100' },
  { id: 'h10', name: 'Flat White',           description: 'Velvety microfoam milk over a double ristretto.',     price: '5,000', category: 'hot-drinks',  image: 'https://picsum.photos/id/425/100/100' },
  { id: 'h11', name: 'Latte',               description: 'Smooth espresso with steamed milk and light foam.',    price: '5,500', category: 'hot-drinks',  image: 'https://picsum.photos/id/431/100/100' },
  { id: 'h12', name: 'Spanish Latte',        description: 'Espresso with condensed milk and steamed milk.',       price: '6,500', category: 'hot-drinks',  image: 'https://picsum.photos/id/1060/100/100' },
  { id: 'h13', name: 'African Latte',        description: 'Latte infused with African spices and honey.',         price: '8,000', category: 'hot-drinks',  image: 'https://picsum.photos/id/432/100/100' },
  { id: 'h14', name: 'Caramel Macchiato',    description: 'Vanilla syrup, milk, espresso and caramel drizzle.',  price: '8,500', category: 'hot-drinks',  image: 'https://picsum.photos/id/425/100/100' },
  { id: 'h15', name: 'Vanilla Latte',        description: 'Latte sweetened with house-made vanilla syrup.',       price: '7,500', category: 'hot-drinks',  image: 'https://picsum.photos/id/431/100/100' },
  { id: 'h16', name: 'Mocha',               description: 'Espresso with chocolate sauce and steamed milk.',      price: '9,000', category: 'hot-drinks',  image: 'https://picsum.photos/id/1060/100/100' },
  { id: 'h17', name: 'Nutmeg Latte',         description: 'Warm latte dusted with freshly grated nutmeg.',        price: '5,000', category: 'hot-drinks',  image: 'https://picsum.photos/id/432/100/100' },
  { id: 'h18', name: 'Tiramisu Latte',       description: 'Espresso latte with tiramisu flavors.',               price: '10,500', category: 'hot-drinks', image: 'https://picsum.photos/id/425/100/100' },
  { id: 'h19', name: 'Spicy Turmeric Latte', description: 'Golden latte with turmeric, ginger and black pepper.',price: '7,500', category: 'hot-drinks',  image: 'https://picsum.photos/id/431/100/100' },
  { id: 'h20', name: 'White Mocha',          description: 'Espresso with white chocolate sauce and steamed milk.',price: '10,000', category: 'hot-drinks', image: 'https://picsum.photos/id/1060/100/100' },
  { id: 'h21', name: 'Extra Espresso Shot',  description: 'Add an extra espresso shot to any drink.',            price: '2,000', category: 'hot-drinks',  image: 'https://picsum.photos/id/432/100/100' },

  // Iced Drinks
  { id: 'i1',  name: 'Iced Pour Over',          description: 'Cold-brewed pour over served over ice.',              price: '6,000',  category: 'iced-drinks', image: 'https://picsum.photos/id/452/100/100' },
  { id: 'i2',  name: 'Espresso Shakerato',       description: 'Shaken espresso with ice for a frothy cold drink.',  price: '4,500',  category: 'iced-drinks', image: 'https://picsum.photos/id/468/100/100' },
  { id: 'i3',  name: 'Iced Espresso',            description: 'Fresh espresso shot poured over ice.',               price: '3,500',  category: 'iced-drinks', image: 'https://picsum.photos/id/452/100/100' },
  { id: 'i4',  name: 'Cold Brew',                description: '18-hour cold-steeped Rwandan coffee.',               price: '6,000',  category: 'iced-drinks', image: 'https://picsum.photos/id/468/100/100' },
  { id: 'i5',  name: 'Iced Americano',           description: 'Espresso over ice with cold water.',                  price: '5,500',  category: 'iced-drinks', image: 'https://picsum.photos/id/452/100/100' },
  { id: 'i6',  name: 'Cherry Cold Brew',         description: 'Cold brew infused with sweet cherry syrup.',          price: '7,500',  category: 'iced-drinks', image: 'https://picsum.photos/id/468/100/100' },
  { id: 'i7',  name: 'Raspberry Cold Brew',      description: 'Cold brew with fresh raspberry flavor.',              price: '9,000',  category: 'iced-drinks', image: 'https://picsum.photos/id/452/100/100' },
  { id: 'i8',  name: 'Iced Latte',               description: 'Espresso with cold milk poured over ice.',            price: '6,000',  category: 'iced-drinks', image: 'https://picsum.photos/id/468/100/100' },
  { id: 'i9',  name: 'Iced Spanish Latte',       description: 'Condensed milk latte served cold over ice.',          price: '7,000',  category: 'iced-drinks', image: 'https://picsum.photos/id/452/100/100' },
  { id: 'i10', name: 'Iced Mocha',               description: 'Chocolate espresso drink served chilled over ice.',   price: '9,500',  category: 'iced-drinks', image: 'https://picsum.photos/id/468/100/100' },
  { id: 'i11', name: 'Iced Caramel Macchiato',   description: 'Cold caramel macchiato with vanilla and milk.',       price: '9,000',  category: 'iced-drinks', image: 'https://picsum.photos/id/452/100/100' },
  { id: 'i12', name: 'Iced Tiramisu Latte',      description: 'Chilled tiramisu-flavored espresso latte.',           price: '11,000', category: 'iced-drinks', image: 'https://picsum.photos/id/468/100/100' },
  { id: 'i13', name: 'Iced Vanilla Latte',       description: 'Vanilla latte served cold over ice.',                 price: '8,000',  category: 'iced-drinks', image: 'https://picsum.photos/id/452/100/100' },
  { id: 'i14', name: 'Iced Nutmeg Latte',        description: 'Cold nutmeg latte with a warm spice finish.',         price: '5,500',  category: 'iced-drinks', image: 'https://picsum.photos/id/468/100/100' },
  { id: 'i15', name: 'Plum Noir',                description: 'Cold brew with plum and dark fruit notes.',           price: '9,000',  category: 'iced-drinks', image: 'https://picsum.photos/id/452/100/100' },
  { id: 'i16', name: 'Iced White Mocha',         description: 'White chocolate mocha served chilled over ice.',      price: '10,500', category: 'iced-drinks', image: 'https://picsum.photos/id/468/100/100' },
  { id: 'i17', name: 'Iced African Espresso',    description: 'Spiced African espresso served over ice.',            price: '6,500',  category: 'iced-drinks', image: 'https://picsum.photos/id/452/100/100' },
  { id: 'i18', name: 'Mont Blanc',               description: 'Signature iced espresso with chestnut cream.',        price: '12,000', category: 'iced-drinks', image: 'https://picsum.photos/id/468/100/100' },
  { id: 'i19', name: 'Coffee Protein Shake',     description: 'Cold brew blended with protein and milk.',            price: '12,000', category: 'iced-drinks', image: 'https://picsum.photos/id/452/100/100' },
  { id: 'i20', name: 'Affogato',                 description: 'Vanilla ice cream drowned in a hot espresso shot.',   price: '12,000', category: 'iced-drinks', image: 'https://picsum.photos/id/468/100/100' },

  // Tea & Other Drinks
  { id: 't1',  name: 'Black Loose Leaf Tea',     description: 'Premium single-estate black loose leaf tea.',         price: '5,500',  category: 'tea-drinks', image: 'https://picsum.photos/id/225/100/100' },
  { id: 't2',  name: 'Babycinno',                description: 'Warm steamed milk with a sprinkle of chocolate.',     price: '5,000',  category: 'tea-drinks', image: 'https://picsum.photos/id/326/100/100' },
  { id: 't3',  name: 'Chai Latte',               description: 'Spiced Indian tea blend with steamed milk.',          price: '6,000',  category: 'tea-drinks', image: 'https://picsum.photos/id/225/100/100' },
  { id: 't4',  name: 'Hot Chocolate',            description: 'Rich Belgian chocolate with steamed milk.',           price: '9,000',  category: 'tea-drinks', image: 'https://picsum.photos/id/326/100/100' },
  { id: 't5',  name: 'African Tea',              description: 'Traditional Rwandan tea with ginger and spices.',     price: '6,500',  category: 'tea-drinks', image: 'https://picsum.photos/id/225/100/100' },
  { id: 't6',  name: 'Green Loose Leaf Tea',     description: 'Light and fresh green tea, whole loose leaf.',        price: '5,500',  category: 'tea-drinks', image: 'https://picsum.photos/id/326/100/100' },
  { id: 't7',  name: 'Spice Tea',                description: 'Warming blend of herbs and aromatic spices.',         price: '6,000',  category: 'tea-drinks', image: 'https://picsum.photos/id/225/100/100' },
  { id: 't8',  name: 'Iced Cascara Spritz',      description: 'Sparkling cascara coffee cherry tea over ice.',       price: '6,500',  category: 'tea-drinks', image: 'https://picsum.photos/id/326/100/100' },
  { id: 't9',  name: 'Iced Lemonade Tea',        description: 'Chilled lemonade blended with fresh-brewed tea.',     price: '7,500',  category: 'tea-drinks', image: 'https://picsum.photos/id/225/100/100' },
  { id: 't10', name: 'Iced Chocolate',           description: 'Cold Belgian chocolate drink over ice.',              price: '9,500',  category: 'tea-drinks', image: 'https://picsum.photos/id/326/100/100' },
  { id: 't11', name: 'Iced Chai Latte',          description: 'Spiced chai latte served cold over ice.',             price: '6,500',  category: 'tea-drinks', image: 'https://picsum.photos/id/225/100/100' },
  { id: 't12', name: 'Hibiscus Spritz',          description: 'Sparkling hibiscus flower drink, tart and floral.',   price: '9,000',  category: 'tea-drinks', image: 'https://picsum.photos/id/326/100/100' },
  { id: 't13', name: 'Cascara Tea',              description: 'Brewed coffee cherry husks, naturally sweet.',        price: '5,000',  category: 'tea-drinks', image: 'https://picsum.photos/id/225/100/100' },
  { id: 't14', name: 'Matcha Raspberry',         description: 'Ceremonial matcha blended with fresh raspberry.',     price: '12,000', category: 'tea-drinks', image: 'https://picsum.photos/id/326/100/100' },
  { id: 't15', name: 'Ginger Soda',              description: 'House-made ginger syrup with sparkling water.',       price: '5,500',  category: 'tea-drinks', image: 'https://picsum.photos/id/225/100/100' },
  { id: 't16', name: 'Ginger Shot',              description: 'Fresh pressed ginger concentrate shot.',              price: '3,000',  category: 'tea-drinks', image: 'https://picsum.photos/id/326/100/100' },
  { id: 't17', name: 'Raspberry Lemonade',       description: 'Fresh lemonade with house-made raspberry syrup.',     price: '12,000', category: 'tea-drinks', image: 'https://picsum.photos/id/225/100/100' },
  { id: 't18', name: 'Iced Matcha Tea',          description: 'Japanese ceremonial matcha served cold over ice.',    price: '9,500',  category: 'tea-drinks', image: 'https://picsum.photos/id/326/100/100' },
  { id: 't19', name: 'Matcha Mango',             description: 'Matcha blended with fresh tropical mango.',           price: '12,000', category: 'tea-drinks', image: 'https://picsum.photos/id/225/100/100' },
  { id: 't20', name: 'Matcha Tea',               description: 'Ceremonial grade matcha prepared traditional style.', price: '9,000',  category: 'tea-drinks', image: 'https://picsum.photos/id/326/100/100' },

  // Soft Drinks
  { id: 's1', name: 'Water',                   description: 'Still mineral water.',                                  price: '2,500',  category: 'soft-drinks', image: 'https://picsum.photos/id/493/100/100' },
  { id: 's2', name: 'Mixed Fruit Juice',        description: 'Freshly blended seasonal fruit juice.',               price: '10,000', category: 'soft-drinks', image: 'https://picsum.photos/id/108/100/100' },
  { id: 's3', name: 'Glass Bottle Water',       description: 'Still or sparkling water in glass bottle.',           price: '2,500',  category: 'soft-drinks', image: 'https://picsum.photos/id/493/100/100' },
  { id: 's4', name: 'Pineapple Juice',          description: 'Freshly pressed pineapple juice.',                    price: '10,000', category: 'soft-drinks', image: 'https://picsum.photos/id/108/100/100' },
  { id: 's5', name: 'Orange Juice',             description: 'Freshly squeezed orange juice.',                      price: '12,000', category: 'soft-drinks', image: 'https://picsum.photos/id/493/100/100' },
  { id: 's6', name: 'Green Juice',              description: 'Blended green vegetables and fruits.',                price: '11,000', category: 'soft-drinks', image: 'https://picsum.photos/id/108/100/100' },
  { id: 's7', name: 'Smoothie',                 description: 'Seasonal fruit smoothie, ask for today\'s blend.',   price: '10,000', category: 'soft-drinks', image: 'https://picsum.photos/id/493/100/100' },

  // Extras
  { id: 'e1', name: 'Low Fat Milk',             description: 'Add low fat milk to any drink.',                      price: '500',   category: 'extras', image: 'https://picsum.photos/id/431/100/100' },
  { id: 'e2', name: 'Vanilla Flavor',           description: 'House-made vanilla syrup add-on.',                   price: '1,500', category: 'extras', image: 'https://picsum.photos/id/431/100/100' },
  { id: 'e3', name: 'Caramel Flavor',           description: 'Rich caramel syrup add-on.',                         price: '1,500', category: 'extras', image: 'https://picsum.photos/id/431/100/100' },
  { id: 'e4', name: 'Oat Milk',                 description: 'Dairy-free oat milk substitute.',                    price: '1,500', category: 'extras', image: 'https://picsum.photos/id/431/100/100' },
  { id: 'e5', name: 'Almond Milk',              description: 'Dairy-free almond milk substitute.',                 price: '1,500', category: 'extras', image: 'https://picsum.photos/id/431/100/100' },
  { id: 'e6', name: 'Spanish Flavor',           description: 'Condensed milk syrup add-on.',                       price: '1,500', category: 'extras', image: 'https://picsum.photos/id/431/100/100' },
  { id: 'e7', name: 'Soy Milk',                 description: 'Dairy-free soy milk substitute.',                    price: '1,500', category: 'extras', image: 'https://picsum.photos/id/431/100/100' },
];